name: flutter_sherpa_onnx_example
description: Demonstrates how to use the flutter_sherpa_onnx plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.15.0-96.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sherpa_onnx:
    path: ../
  path_provider:
  mic_stream:
    path: ../../mic_stream
  permission_handler:
  just_audio: 
  cupertino_icons: ^1.0.2
  wave_builder:
    git:
      url: https://github.com/nmfisher/wave_builder.git
  record: 5.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/asr/    
    - assets/test.pcm